IF(NOT USE_QT5)
   SET(USE_QT4 ON)
ENDIF()
IF(USE_QT4)
   TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
      LIB_REQUIRED_TPLS QT
   )
ELSEIF(USE_QT5)
   TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
      LIB_REQUIRED_TPLS Qt5Gui Qt5Widgets Qt5Core
   )
ENDIF()
